
server:
  port: 8090
  servlet:
    context-path: /rule-engine


spring:
  application:
    name: rule-engine
  datasource:
    url: jdbc:mysql://localhost:3306/test_db?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    throw-exception-if-no-handler-found: true

# mybaits 相关配置
mybatis:
  type-aliases-package: com.xiu.rule.**.pojo.domain
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30

# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: false
  params: count=countSql
  support-methods-arguments: true
  row-bounds-with-count: false
  page-size-zero: false


# api文档配置
swagger:
  enabled: true
  title: 接口文档
  description: 小新的测试学习项目
  termsOfServiceUrl: http://localhost:8090/rule-engine/doc.html
  authorName: Mr.xiu
  authorEmail: xdy_0722@sina.cn
  authorUrl: http://localhost:8090/rule-engine
  version: 1.0.1
  webBasePackage: com.xiu.learn.*.controller.*
  apiBasePackage: com.xiu.learn.*.controller.*